### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by ijemmao** [dali-lab/shopu#14]
* Create a Style Guide for the application
* Follow the instructions from the [DALI Build Site](http://build.dali.dartmouth.edu/milestones/week06/style-guide.html)

**Comment by butalas** [comment]
Is the style guide all done in Figma or is it like a document?

**Comment by ijemmao** [comment]
@butalas Yeah, it's all done in the Figma board - it's just off to the side of the mock ups
