### ISSUE TITLE
Request Profile

### ISSUE THREAD

**Issue by ijemmao** [dali-lab/shopu#40]
* Implement the Request Profile page
* Functionality doesn't have to exist - the Status Update button doesn't have to work
* Use a `FlatList` so the user can scroll through their items
    * Make sure that you use an array of data
* Don't use `absolute` styles

**Comment by butalas** [comment]
So as I'm working on it I keep getting this error: `[22:07:19] Unable to resolve "./components/FontLoad" from "screens/request_profile.js".` This is as I am trying to run my `request_profile.js` code from `App.js.` I'm not really sure what's happening. The paths are correct so I don't understand why it's unable to load.

**Comment by ijemmao** [comment]
Make sure that you call `git pull origin master` to have the most updated code. If that doesn't work we can work on it together in person!

**Comment by butalas** [comment]
Hey Ijemma! I've been having trouble getting the FlatList to render. I have a small data array passed in, but no matter if I wrap Text in a View or something else, the FlatList won't render on my page. There isn't even any error that comes up. I'm not sure what's wrong, so my code is below: 
```
<FlatList
                data={[{name: 1},{name: 2},{name: 3}]}
                keyExtractor={(item, index) => index.toString()}
                renderItem={
                  ({item, index}) => {
                  return (
                      <View>
                      <View style={{backgroundColor: colors[index % colors.length]}}>
                        <View style={styles.tableRows} />
                      </View>
                      </View>
                )
                }
              }
              />
```
